apiVersion: tekton.dev/v1
kind: Task
metadata:
  creationTimestamp: '2025-11-28T22:57:41Z'
  generation: 1
  managedFields:
    - apiVersion: tekton.dev/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:description': {}
          'f:steps': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2025-11-28T22:57:41Z'
  name: cleanup
  namespace: sn-labs-serguei246
  resourceVersion: '2508019588'
  uid: b391d8e1-5f8a-4a2c-a7ce-a9b727bd49ae
spec:
  description: This task will clean up a workspace by deleting all of the files.
  steps:
    - computeResources: {}
      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)
      image: 'alpine:3'
      name: remove
      script: |
        #!/usr/bin/env sh
        set -eu
        echo "Removing all files from ${WORKSPACE_SOURCE_PATH} ..."
        # Delete any existing contents of the directory if it exists.
        #
        # We don't just "rm -rf ${WORKSPACE_SOURCE_PATH}" because ${WORKSPACE_SOURCE_PATH} might be "/"
        # or the root of a mounted volume.
        if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
          # Delete non-hidden files and directories
          rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
          # Delete files and directories starting with . but excluding ..
          rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
          # Delete files and directories starting with .. plus any other character
          rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
        fi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      workingDir: $(workspaces.source.path)
  workspaces:
    - name: source
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: nose
spec:
  description: This task will run nosetests on the provided input.
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments to pass to nose
      type: string
      default: "-v"
    - name: database_uri
      description: Database connection string
      type: string
      default: "sqlite:///test.db"

  # Apply PodSecurity-friendly defaults to ALL step containers
  stepTemplate:
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - "ALL"
      seccompProfile:
        type: RuntimeDefault

  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      env:
        - name: DATABASE_URI
          value: $(params.database_uri)
        - name: HOME
          value: /tmp/python
      script: |
        #!/usr/bin/env sh
        set -eu

        mkdir -p "${HOME}"
        export PATH="${HOME}/.local/bin:${PATH}"

        echo "***** Installing dependencies *****"
        python -m pip install --upgrade pip wheel
        pip install --user -qr requirements.txt

        echo "***** Running nosetests with: $(params.args)"
        nosetests $(params.args)
